language: node_js
node_js: stable

env:
  - TZ=Asia/Shanghai

install:
  - npm install hexo-cli -g
  - npm install yarn -g
  - yarn install

before_script:
  - git config --global user.email "lengthmin@gmail.com"
  - git config --global user.name "Artin"
  - sh ./helper/replace_secret.sh
  - sh ./helper/update_lib.sh

script:
  - yarn d

after_script:
  - cat ./_config.yml

branches:
  only:
    - hexo
