# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Artin's Blog
subtitle: 我便一步一莲花祈祷
description: Python / React / Nodejs / 机器学习
keywords: Python,机器学习,React,Nodejs
author: Artin
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://lengthmin.me
root: /
permalink: posts/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
  - README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date


# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page


# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

feed:
  type: rss2
  path: rss.xml
  limit: 0
  hub:

# search
search:
  path: search.xml
  field: post
  format: html
  limit: 10000


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  # other deployer
  - type: git
    repo:
      github: https://_GH_TOKEN_@github.com/lengthmin/lengthmin.me.git,master
      coding: https://Artin:_CODING_TOKEN_@git.dev.tencent.com/Artin/artin.git,master


sitemap:
  path: sitemap.xml
  tag: false
  category: false  
baidusitemap:
  path: baidusitemap.xml

pwa:
  manifest:
    path: /manifest.json
  serviceWorker:
    path: /sw.js
    preload:
      urls:
        - /
        - /archives/
        - /categories/
      posts: 5
    opts:
      networkTimeoutSeconds: 5
    routes:
      - pattern: '*.artin.workers.dev'
        strategy: networkFirst
      - pattern: '!!js/regexp /.*\.(js|css|jpg|jpeg|png|gif|svg|eot|ttf|woff|woff2)$/'
        strategy: cacheFirst
      - pattern: '!!js/regexp /\//'
        strategy: networkFirst

  priority: 5

symbols_count_time:
  symbols: true
  time: true
  total_symbols: false
  total_time: false
  exclude_codeblock: true



neat_enable: true
neat_html:
  enable: true
  logger: false
  exclude:
    - "index.test.html"
neat_css:
  enable: true
  exclude:
    - "*.min.css"
neat_js:
  enable: true
  exclude:
    - "*.min.js"
neat_gzip:
  enable: true
  include:
    - "*.html"
    - "*.css"
    - "*.js"
    - "*.txt"
    - "*.ttf"
    - "*.atom"
    - "*.stl"
    - "*.xml"
    - "*.svg"
    - "*.eot"
    - "*.json"
neat_brotli:
  enable: true
  include:
    - '*.html'
    - '*.css'
    - '*.js'
    - '*.txt'
    - '*.ttf'
    - '*.atom'
    - '*.stl'
    - '*.xml'
    - '*.svg'
    - '*.eot'
    - '*.json'

markdown_it_plus:
  highlight: true
  html: true
  xhtmlOut: true
  breaks: true
  langPrefix:
  linkify: true
  typographer: true
  quotes: “”‘’
  pre_class: highlight


theme_config:
  anchor:
    enable: true
    color: '#0e83cd'
    position: right # If left, anchors will always be visible.
    margin: 7px 
    text: '#'
    icon:
      enable: true 
      font: FontAwesome
      content: \f0c1 # CSS content for FontAwesome & ForkAwesome.

  cache:
    enable: true

  google_analytics_:
    tracking_id: _google_analytics_tracking_id_
    localhost_ignored: true

  custom_file_path:
    head: source/_data/head.swig
    #header: source/_data/header.swig
    # sidebar: source/_data/sidebar.swig
    #postMeta: source/_data/post-meta.swig
    postBodyEnd: source/_data/post-body-end.swig
    footer: source/_data/footer.swig
    #bodyEnd: source/_data/body-end.swig
    #variable: source/_data/variables.styl
    #mixin: source/_data/mixins.styl
    style: source/_data/styles.styl

  footer:
    since: 2016

    icon:
      name: heart
      animated: false
      color: "#ff0000"

    powered:
      enable: true
      version: false

    theme:
      enable: true
      version: false
    beian:
      enable: false
      icp:

  post_meta:
    item_text: true
    created_at: true
    updated_at:
      enable: false
      another_day: false
    categories: true
    

  seo: true
  disable_baidu_transformation: true
  canonical: true
  exturl: false

  menu:
    home: / || home
    tags: /tags/ || tags
    categories: /categories/ || th
    archives: /archives/ || archive

  # Enable / Disable menu icons / item badges.
  menu_settings:
    icons: true
    badges: true

  scheme: Pisces

  reading_progress:
    enable: true
    position: top
    color: "#37c6c0"
    height: 2px
      
  pjax: true

  site_state: true

  social:
    Email: mailto:withwinds@outlook.com || envelope
    GitHub: https://github.com/lengthmin || github
    Twitter: https://twitter.com/lengthmin2 || twitter
    Telegram: https://telegram.me/lengthmin || telegram

  social_icons:
    enable: true
    icons_only: false
    transition: false

  # Sidebar Avatar
  avatar:
    url: /images/avatar.png
    # If true, the avatar would be dispalyed in circle.
    rounded: false
    # If true, the avatar would be rotated with the cursor.
    rotated: false
    display: hide

    offset: 12
    onmobile: false


  back2top:
    enable: true
    sidebar: true
    scrollpercent: true

  read_more_btn: true

  symbols_count_time:
    separated_meta: true
    item_text_post: true
    item_text_total: false
    awl: 2
    wpm: 275
    suffix: mins.

  # Related popular posts
  # Dependencies: https://github.com/tea3/hexo-related-popular-posts
  related_posts:
    enable: true
    title: # custom header, leave empty to use the default one
    display_in_home: false
    params:
      maxCount: 5
      #PPMixingRate: 0.0
      isDate: false
      #isImage: false
      #isExcerpt: false

  mobile_layout_economy: true

  motion:
    enable: false
    async: true
    transition:
      post_block: fadeIn
      post_header: slideDownIn
      post_body: slideDownIn
      coll_header: slideLeftIn
      sidebar: slideUpIn


  codeblock:
    highlight_theme: normal
    copy_button:
      enable: true
      show_result: true
      style: flat

  # Blog rolls
  links_icon: link
  links_title: 友链
  links_layout: inline
  links_:
    Max: http://maxlv.org/ || MaxLv 
    "Konica 的自留地": http://www.iikira.com/ || 一个大可爱
    Sukka: https://skk.moe/ || 坏耶
    DIYgod: https://diygod.me/ || 带我领略 Github 的 DIYgay 

  text_align:
    desktop: justify
    mobile: start
  android_chrome_color: "#222"
  safari_rainbow: true
  custom_scrollbar: true
  highlight_theme: normal
  cheers: true




  note:
    style: modern
    icons: true
    border_radius: 3
    light_bg_offset: 0

  # Tabs tag
  tabs:
    enable: true
    transition:
      tabs: true
      labels: true
    border_radius: 0


  # Math Equations Render Support
  math:
    enable: true

    # Default (true) will load mathjax / katex script on demand.
    # That is it only render those page which has `mathjax: true` in Front Matter.
    # If you set it to false, it will load mathjax / katex srcipt EVERY PAGE.
    per_page: true

    # engine: mathjax
    engine: katex

    # hexo-rendering-pandoc (or hexo-renderer-kramed) needed to full MathJax support.
    mathjax:
      # cdn: //cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
      cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML
      # See: https://mhchem.github.io/MathJax-mhchem/
      #mhchem: //cdn.jsdelivr.net/npm/mathjax-mhchem@3
      mhchem: //cdnjs.cloudflare.com/ajax/libs/mathjax-mhchem/3.3.0

    # hexo-renderer-markdown-it-plus (or hexo-renderer-markdown-it with markdown-it-katex plugin) needed to full Katex support.
    katex:
      # cdn: //cdn.jsdelivr.net/npm/katex@0/dist/katex.min.css
      cdn: //cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css

      copy_tex:
        # See: https://github.com/KaTeX/KaTeX/tree/master/contrib/copy-tex
        enable: true
        copy_tex_js: //cdn.jsdelivr.net/npm/katex@0/dist/contrib/copy-tex.min.js
        copy_tex_css: //cdn.jsdelivr.net/npm/katex@0/dist/contrib/copy-tex.min.css



  pangu: true

  # TagCloud settings for tags page.
  tagcloud:
    # If true, font size, font color and amount of tags can be customized
    enable: true
    # All values below are same as default, change them by yourself
    min: 30 # Minimun font size in px
    max: 42 # Maxium font size in px
    start: "#ccc" # Start color (hex, rgba, hsla or color keywords)
    end: "#111" # End color (hex, rgba, hsla or color keywords)
    amount: 200 # Amount of tags, change it if you have more than 200 tags


  gitalk:
    enable: true
    github_id: lengthmin # Github repo owner
    repo: lengthmin.me # Repository name to store issues
    client_id: _gitalk_client_id_ # Github Application Client ID
    client_secret: _gitalk_client_secret_ # Github Application Client Secret
    admin_user: lengthmin # GitHub repo owner and collaborators, only these guys can initialize github issues
    distraction_free_mode: false # Facebook-like distraction free mode
    # Gitalk's display language depends on user's browser or system environment
    # If you want everyone visiting your site to see a uniform language, you can set a force language value
    # Available values: en, es-ES, fr, ru, zh-CN, zh-TW
    language:


  busuanzi_count:
    enable: true
    total_visitors: true
    total_visitors_icon: user
    total_views: true
    total_views_icon: eye
    post_views: true
    post_views_icon: eye


  post_edit:
    enable: true
    url: https://github.com/lengthmin/lengthmin.me/tree/backup/source/


  local_search:
    enable: true
    # if auto, trigger search by changing input
    # if manual, trigger search by pressing enter key or search button
    trigger: auto
    # show top n results per article, show all results by setting to -1
    top_n_per_article: 3
    # unescape html strings to the readable one
    unescape: true

  fancybox: true
  lazyload: true
  
  pace:
    enable: true
    theme: flash

  vendors:
    gitalk_js: //cdnjs.loli.net/ajax/libs/gitalk/1.5.0/gitalk.min.js
    gitalk_css: //cdnjs.loli.net/ajax/libs/gitalk/1.5.0/gitalk.min.css
